apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ownedentitypicker-example
  title: OwnedEntityPicker Feature
  description: Select from entities you own
spec:
  owner: user:default/c-nell
  type: service
  
  parameters:
    - title: Owned Entity Selection
      properties:
        myComponent:
          title: My Component
          type: string
          description: Select from components you own
          ui:field: OwnedEntityPicker
          ui:options:
            allowedKinds:
              - Component
          ui:help: 'Only shows components owned by you or your teams'
        
        mySystem:
          title: My System
          type: string
          description: Select from systems you own
          ui:field: OwnedEntityPicker
          ui:options:
            allowedKinds:
              - System
        
        myResource:
          title: My Resource
          type: string
          description: Select from resources you own
          ui:field: OwnedEntityPicker
          ui:options:
            allowedKinds:
              - Resource
            catalogFilter:
              spec.type: database
  
  steps:
    - id: log
      name: Log Owned Entities
      action: debug:log
      input:
        message: |
          My Component: ${{ parameters.myComponent }}
          My System: ${{ parameters.mySystem }}
          My Resource: ${{ parameters.myResource }}