apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: repoownerpicker-example
  title: RepoOwnerPicker Feature
  description: Select repository owners with autocomplete
spec:
  owner: user:default/c-nell
  type: service
  
  parameters:
    - title: Owner Selection
      properties:
        repoOwner:
          title: Repository Owner
          type: string
          description: Select repo owner with autocomplete
          ui:field: RepoOwnerPicker
          ui:options:
            host: github.com
            excludedOwners:
              - backstage
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
          ui:help: 'Autocomplete for GitHub organizations and users'