apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: api-select-example
  title: API-Driven Select Field
  description: Populate dropdown from external API
spec:
  owner: user:default/c-nell
  type: service
  
  parameters:
    - title: Dynamic Selection
      properties:
        cloudRegion:
          title: Cloud Region
          type: string
          description: Regions fetched from API
          ui:field: SelectFieldFromApi
          ui:options:
            path: 'catalog/entity-facets'
            params:
              facet: 'kind'
            valueSelector: 'facets[0].values[*].value'
            labelSelector: 'facets[0].values[*].count'