apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: autocomplete-example
  title: Autocomplete Example
spec:
  owner: user:default/c-nell
  type: service
  
  parameters:
    - title: Personal Information
      properties:
        firstName:
          type: string
          title: First Name
          ui:autofocus: true
          ui:emptyValue: ''
          ui:autocomplete: given-name
        
        lastName:
          type: string
          title: Last Name
          ui:emptyValue: ''
          ui:autocomplete: family-name
        
        email:
          type: string
          title: Email
          format: email
          ui:autocomplete: email
        
        telephone:
          type: string
          title: Telephone
          minLength: 10
          ui:options:
            inputType: tel
          ui:autocomplete: tel