apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-github-proxy
  title: Test GitHub Proxy
spec:
  owner: user:default/c-nell
  type: service
  
  steps:
    - id: test
      action: http:backstage:request
      input:
        method: GET
        path: /proxy/github
    
    - id: log
      action: debug:log
      input:
        message: |
          ${{ steps['test'].output | dump(2) }}
  
  output:
    text:
      - title: Output
        content: |
          ${{ steps['test'].output | dump(2) }}
