apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: http-advanced-test
  title: HTTP Advanced Action Test
  description: Calls the GitHub API using the advanced HTTP action
spec:
  owner: user:default/cnell
  type: service

  parameters:
    - title: GitHub Repo Info
      required:
        - repo
      properties:
        repo:
          title: Repository
          type: string
          description: org/repo (e.g. backstage/backstage)

  steps:
    - id: fetchRepo
      name: Fetch GitHub Repository
      action: http:backstage:request:advanced
      input:
        method: GET
        url: https://api.github.com/repos/${{ parameters.repo }}
        responseType: json
        verbose: true
        auth:
          type: bearer
          token: ${{ secrets.githubToken }}
        retry:
          enabled: true
          maxRetries: 3
  output:
    text:
      - title: Repository JSON
        content: |
          Repo full name: ${{ steps.fetchRepo.output.httpResponse.data.full_name }}
          Stars: ${{ steps.fetchRepo.output.httpResponse.data.stargazers_count }}
